---
all:
  children:
    K8S-master:
      hosts:
        k8s-server-1:
          ansible_host: 89.169.150.50
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_python_interpreter: /usr/bin/python3.12
          ansible_user: ubuntu
    K8S-nodes:
      hosts:
        kubernetes-node-1:
          ansible_host: 158.160.99.109
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
        kubernetes-node-2:
          ansible_host: 158.160.90.124
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
        kubernetes-node-3:
          ansible_host: 158.160.207.251
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu