---
all:
  children:
    K8S-master:
      hosts:
        k8s-server-1:
          ansible_host: 89.169.158.226
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
    K8S-nodes:
      hosts:
        kubernetes-node-1:
          ansible_host: 51.250.9.38
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
        kubernetes-node-2:
          ansible_host: 89.169.160.161
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
        kubernetes-node-3:
          ansible_host: 158.160.152.150
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu