---
all:
  children:
    K8S-master:
      hosts:
        k8s-server-1:
          ansible_host: 89.169.142.199
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
    K8S-nodes:
      hosts:
        kubernetes-node-1:
          ansible_host: 89.169.152.200
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
        kubernetes-node-2:
          ansible_host: 89.169.175.233
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu
        kubernetes-node-3:
          ansible_host: 158.160.151.238
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_user: ubuntu